INSERT INTO accounts (name, surname, role) VALUES
  ('John',    'Doe',       'admin'),
  ('Jane',    'Smith',     'user'),
  ('Jim',     'Beam',      'user'),
  ('Jack',    'Sparrow',   'user'),
  ('John',    'Wick',      'admin'),
  ('Mary',    'Jane',      'user'),
  ('Peter',   'Parker',    'user'),
  ('Tony',    'Stark',     'admin'),
  ('Bruce',   'Wayne',     'user'),
  ('Clark',   'Kent',      'user'),
  ('Barry',   'Allen',     'user'),
  ('Wally',   'West',      'user'),
  ('Arthur',  'Curry',     'admin'),
  ('Hal',     'Jordan',    'user'),
  ('Violet',  'Parr',      'user'),
  ('Dash',    'Parr',      'user'),
  ('Brandon', 'Belcher',   'user'),
  ('Carmen',  'Sandiego',  'admin'),
  ('Walter',  'White',     'user'),
  ('Jesse',   'Pinkman',   'user')
ON CONFLICT DO NOTHING;
